feat: add reading progress bar

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,8 +1,10 @@
-name: Git feature testing
+name: Testing sonarqube and coverage test alongside feature
+
 on:
   push:
     branches:
-      - feature-readingbar
+      - pso
+
 
 jobs:
 # ===========================================
@@ -95,3 +97,65 @@ jobs:
           SESSION_DRIVER: array
           QUEUE_CONNECTION: sync
         run: php artisan test --coverage-clover=coverage.xml
+
+      - name: SonarCloud Scan
+        uses: SonarSource/sonarcloud-github-action@master
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+        with:
+          args: >
+            -Dsonar.projectKey=eLlawliet_BookStack
+            -Dsonar.organization=ellawliet
+            -Dsonar.php.coverage.reportPaths=coverage.xml
+            -Dsonar.sources=app,routes
+            -Dsonar.tests=tests
+  # ==========================================
+  # CONTINUOUS DEPLOYMENT (CD)
+  # ==========================================
+  cd-deployment:
+    name: Deploy to Azure
+    needs: ci-testing
+    if: always()
+    runs-on: ubuntu-latest
+    steps:
+      - name: Verify CI Passed
+        run: |
+          if [ "${{ needs.ci-testing.result }}" != "success" ]; then
+            echo "❌ ERROR: Continuous Integration (CI) tests failed!"
+            echo "🛑 Aborting Continuous Deployment (CD) to protect the live server."
+            exit 1
+          fi
+          echo "✅ CI passed! Proceeding with deployment..."
+
+      - name: Checkout Repository
+        uses: actions/checkout@v4
+
+      - name: Setup PHP
+        uses: shivammathur/setup-php@v2
+        with:
+          php-version: '8.2'
+          extensions: mbstring, xml, pdo_mysql, gd, iconv, tokenizer, zip
+
+      - name: Setup Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: '20'
+
+      - name: Build Frontend Assets
+        run: |
+          npm install
+          npm run build
+
+      - name: Optimize for Production
+        run: composer install --no-dev --optimize-autoloader
+
+      - name: Package Application
+        run: zip -r release.zip . -x "*.git*" "tests/*" "node_modules/*"
+
+      - name: Deploy to Azure App Service
+        uses: azure/webapps-deploy@v2
+        with:
+          app-name: 'bookstack-project-pso'
+          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
+          package: release.zip
